/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Admin
 */
public class login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
    public login() {
        initComponents();
        
        con = Dbms.mycon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        juser = new javax.swing.JTextField();
        jshow = new javax.swing.JCheckBox();
        jpass = new javax.swing.JPasswordField();
        jlog = new javax.swing.JButton();
        jlog1 = new javax.swing.JButton();
        jlog2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("VIEW AVAILABLE UNITS");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        juser.setBackground(new java.awt.Color(204, 204, 204));
        juser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        juser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juserActionPerformed(evt);
            }
        });
        getContentPane().add(juser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, 230, 30));

        jshow.setForeground(new java.awt.Color(255, 255, 255));
        jshow.setText("Show password");
        jshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowActionPerformed(evt);
            }
        });
        getContentPane().add(jshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 410, 110, -1));

        jpass.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 370, 230, 30));

        jlog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlog.setText("TENANT LOG IN");
        jlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogActionPerformed(evt);
            }
        });
        getContentPane().add(jlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 440, 230, -1));

        jlog1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlog1.setText("Create Account");
        jlog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlog1ActionPerformed(evt);
            }
        });
        getContentPane().add(jlog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 520, 120, -1));

        jlog2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlog2.setText("LANDLORD LOG IN");
        jlog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlog2ActionPerformed(evt);
            }
        });
        getContentPane().add(jlog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 480, 230, -1));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 105)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("is right here.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 520, 100));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 110)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The best place");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 650, 110));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("USERNAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 100, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\background (2).png")); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        setSize(new java.awt.Dimension(1920, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogActionPerformed
        // TODO add your handling code here:
        
        String un = juser.getText();
        String ps = jpass.getText();
        
        try {
            String sql = "SELECT * FROM login WHERE Username=? AND Password=?";
            pst = con.prepareStatement(sql); // Use prepareStatement instead of prepareCall
    
              pst.setString(1, un);
              pst.setString(2, ps);
    
            rs = pst.executeQuery();
    
    if (rs.next()) {
        JOptionPane.showMessageDialog(rootPane, "Your login was successful.");
        new TenantDash().setVisible(true);
    } else {
        JOptionPane.showMessageDialog(rootPane, "Your login failed.");
    }
    } catch (Exception e) {
    // Print the stack trace for debugging
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "An error occurred: " + e.getMessage());
}

        /*if (juser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out username");
        }
        else if(jpass.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill out password");
        }*/
    }//GEN-LAST:event_jlogActionPerformed

    private void juserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juserActionPerformed

    private void jlog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlog1ActionPerformed
        // TODO add your handling code here:
        new signin().setVisible(true);
    }//GEN-LAST:event_jlog1ActionPerformed

    private void jshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowActionPerformed
        // TODO add your handling code here:
        if(jshow.isSelected()) {
            jpass.setEchoChar((char)0);
        }
        else {
            jpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jshowActionPerformed

    private void jlog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlog2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlog2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jlog;
    private javax.swing.JButton jlog1;
    private javax.swing.JButton jlog2;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JCheckBox jshow;
    private javax.swing.JTextField juser;
    // End of variables declaration//GEN-END:variables
}
